### ISSUE TITLE
Subscription period name is not visible when a product is in the Cart

### ISSUE THREAD

**Issue by 5309** [VirtoCommerce/vc-theme-default#67] opened 2018-12-29 07:35 UTC
### Steps to reproduce
1. Go to https://demo.virtocommerce.com/Electronics/en-US/cell-phones
2. Put product "Microsoft Lumia 640 XL RM-1065 8GB Dual SIM" to the Cart
3. Go to the Cart

### Expected behavior

I see text **"Subscription with a period: 1 month"** in a yellow box assigned to a product

### Actual behavior

I see text **"Subscription with a period: 1 2"** in a yellow box assigned to a product

![image](https://user-images.githubusercontent.com/30014191/50534968-e48cf400-0b76-11e9-8f7f-6cc32de0e8ff.png)

**Comment by tatarincev** [comment] 2018-12-29 08:14
Duplicated issue. The same problem described and already resolved (on review) https://github.com/VirtoCommerce/vc-storefront-core/issues/109

**Comment by MarkusReuter** [comment] 2019-03-11 23:43
Seems not to be a duplicate of [https://github.com/VirtoCommerce/vc-storefront-core/issues/109](url)  . This Error is still reproduceable with the latest release 3.2.9.

**Comment by yecli** [comment] 2019-03-12 07:06
@blazemachine Please check if fix from #109 would solve this problem if it is applied to [PaymentPlan](https://github.com/VirtoCommerce/vc-storefront-core/blob/b9516c7533b9533d088f6f22f9c623494cbb2311/VirtoCommerce.Storefront.Model/Subscriptions/PaymentPlan.cs#L19)

**Comment by ilyawzrd** [comment] 2019-03-12 16:41
@yecli, now it's showing correctly
![check](https://user-images.githubusercontent.com/22875828/54218431-3bf3fc80-44f6-11e9-98c8-9f9902f64fdf.png)

**Comment by yecli** [comment] 2019-06-04 11:51
Released in [storefront v3.2.10](https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v3.2.10).

**Closed by yecli** 2019-06-04 11:51 UTC
Labels: bug
